<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $rows = [
            // ESPAÑOL
            ['es', 'tutorials.topic.clan_system.intro', 'El **Sistema de Clanes** federará varias CPs bajo una misma organización. Desde [/clan](/clan) el líder de CP crea el clan o se une pegando el código de 8 caracteres que le da otro líder. Hay tres roles en el clan: **owner** (quien lo crea y tiene control total), **admin** (puede gestionar eventos, vault y mercado) y **miembro** (puede participar en todo pero no administrar).'],
            ['es', 'tutorials.topic.clan_system.bullet.0', '**Crear o unirse a un clan:** Ve a [/clan](/clan). Si tu CP no pertenece a ningún clan verás dos pestañas — «Crear clan» (elige un nombre único; el sistema genera automáticamente el código de invitación de 8 caracteres) o «Unirse» (pega el código que te haya dado el owner del clan). Una vez dentro, en [/clan/settings](/clan/settings) el owner puede copiar el código, compartirlo y regenerarlo si quiere invalidar el anterior.'],
            ['es', 'tutorials.topic.clan_system.bullet.1', '**Crear y gestionar eventos:** En [/clan/events](/clan/events) pulsa «Nuevo evento». Elige el tipo (Raid Boss, Epic Raid, Siege, Call to Arms), pon nombre, DKP a repartir al finalizar y fecha/hora opcional. Si tiene fecha futura aparece en la pestaña «Programados» y los miembros pueden hacer RSVP («Voy» / «No voy»). El flujo completo: admin abre el evento → los miembros confirman su asistencia → los líderes de CP con permiso aprueban a sus miembros (solo los suyos) → el admin pulsa «Finalizar» → el DKP se asigna automáticamente a todos los asistentes con estado «Aprobado». En la pestaña «CP Impact» ves el ranking de asistencia por CP.'],
            ['es', 'tutorials.topic.clan_system.bullet.2', '**Raid Boss Tracker:** En [/clan/raid-bosses](/clan/raid-bosses) el admin añade bosses (nombre, nivel, horas de respawn — 4h por defecto). Cualquier miembro puede actualizar el estado: «Matar» graba el timestamp exacto y calcula la ventana de respawn mostrando un countdown en tiempo real; «Vivo» (alguien lo vio en el mundo pero sin hora de muerte conocida) y «Desconocido» para resetearlo. Los bosses épicos aparecen como cards grandes arriba; los normales en tabla. El countdown es visible para todo el clan y se actualiza cada segundo.'],
            ['es', 'tutorials.topic.clan_system.bullet.3', '**DKP de Clan — cómo funciona el balance:** El balance de cada miembro se ve en [/clan/members](/clan/members) (columna «DKP Clan»). Se calcula automáticamente: eventos finalizados con asistencia «Aprobada» suman el DKP configurado en el evento; las pujas ganadas en subasta del vault lo restan; los ajustes manuales del owner/admin suman o restan según el importe (positivo o negativo). Desde el icono de ajuste junto al balance abres un modal para añadir/quitar puntos con razón escrita obligatoria. El historial completo y la opción de revertir cada ajuste están disponibles haciendo clic en el nombre del miembro.'],
            ['es', 'tutorials.topic.clan_system.bullet.4', '**Vault compartido — depositar y distribuir ítems:** En [/clan/vault](/clan/vault) el admin deposita ítems (búsqueda por nombre en el catálogo o nombre libre). Una vez en el vault el ítem tiene tres destinos posibles: «Asignar» (elige la CP de destino directamente), «Sortear» (el sistema elige una CP aleatoriamente entre todas las del clan) y «Subastar» (define puja mínima en DKP de clan y fecha/hora de cierre). En la pestaña «Subastas» aparecen todas las subastas activas con countdown; cualquier miembro puede pujar con su DKP disponible; cuando el admin cierra la subasta el DKP del ganador se descuenta automáticamente de su balance.'],
            ['es', 'tutorials.topic.clan_system.bullet.5', '**Mercado interno (WTS/WTB):** Desde [/clan/market](/clan/market) cualquier miembro puede publicar un anuncio. Rellenas tipo (WTS = vendo, WTB = compro), categoría (ítem o cuenta), nombre del ítem o cuenta, cantidad, precio fijo o marca «Negociable», y tu información de contacto (nick en juego, Discord, etc). Los anuncios solo son visibles para los miembros del clan — nada sale al exterior. Cuando cierres el trato, márcalo como «Vendido» con el botón de tu anuncio; el owner/admin puede eliminar cualquier listado.'],
            ['es', 'tutorials.topic.clan_system.bullet.6', '**Privacidad garantizada de cada CP:** El clan nunca accede al loot interno, DKP de CP, adena del fondo ni configuración de cada party — esos datos son 100% privados de la CP. Lo único que el clan comparte: quién asistió a eventos de clan y con qué estado (aprobado/pendiente/rechazado), los ítems depositados voluntariamente en el vault, y los listados del mercado interno. Cada CP sigue siendo totalmente independiente dentro del clan.'],

            // ENGLISH
            ['en', 'tutorials.topic.clan_system.intro', 'The **Clan System** federates multiple CPs under one organization. From [/clan](/clan) a CP leader creates the clan or joins by pasting an 8-character code from another leader. Three roles exist in the clan: **owner** (the founder with full control), **admin** (manages events, vault, and market) and **member** (participates in everything but cannot administrate).'],
            ['en', 'tutorials.topic.clan_system.bullet.0', '**Create or join a clan:** Go to [/clan](/clan). If your CP doesn\'t belong to a clan yet you\'ll see two tabs — «Create clan» (pick a unique name; the system auto-generates the 8-character invite code) or «Join» (paste the code given to you by the clan owner). Once inside, the owner can copy, share and regenerate the code at any time from [/clan/settings](/clan/settings).'],
            ['en', 'tutorials.topic.clan_system.bullet.1', '**Creating and managing events:** In [/clan/events](/clan/events) click «New event». Choose the type (Raid Boss, Epic Raid, Siege, Call to Arms), set a name, DKP reward on finalization, and an optional date/time. Future events appear in the «Scheduled» tab where members submit RSVP («Going»/«Not going»). Full flow: admin opens the event → members confirm attendance → CP leaders with approval permission approve their own members → admin clicks «Finalize» → DKP is automatically assigned to all «Approved» attendees. The «CP Impact» tab shows attendance rankings per CP.'],
            ['en', 'tutorials.topic.clan_system.bullet.2', '**Raid Boss Tracker:** In [/clan/raid-bosses](/clan/raid-bosses) admins add bosses (name, level, respawn hours — 4h default). Any member can update status: «Kill» logs the exact timestamp and computes the respawn window showing a real-time countdown; «Alive» (someone spotted it but no death time is known); «Unknown» to reset. Epic bosses show as large cards at the top; normal bosses in a table. The countdown updates every second and is visible to the entire clan.'],
            ['en', 'tutorials.topic.clan_system.bullet.3', '**Clan DKP — how the balance works:** Each member\'s balance appears in [/clan/members](/clan/members) (column «Clan DKP»). Calculated automatically: finalized events with «Approved» attendance add the event\'s configured DKP; won vault auction bids subtract it; manual owner/admin adjustments add or subtract based on the amount (positive or negative). Click the adjustment icon next to the balance to open a modal and add/remove points with a mandatory written reason. Full history and the option to revert each individual adjustment are available by clicking the member\'s name.'],
            ['en', 'tutorials.topic.clan_system.bullet.4', '**Shared Vault — depositing and distributing items:** In [/clan/vault](/clan/vault) admins deposit items (search by name in the catalogue or type a free name). Once in the vault an item has three possible destinations: «Assign» (pick the target CP directly), «Raffle» (the system randomly picks one CP among all clan CPs) and «Auction» (set a minimum DKP bid and a closing date/time). The «Auctions» tab lists all live auctions with a countdown; any member can bid with their available DKP; when the admin closes the auction the winner\'s DKP is automatically deducted from their balance.'],
            ['en', 'tutorials.topic.clan_system.bullet.5', '**Internal Market (WTS/WTB):** From [/clan/market](/clan/market) any member can post a listing. Fill in the type (WTS = selling, WTB = buying), category (item or account), item or account name, quantity, fixed price or mark «Negotiable», and your contact info (in-game nick, Discord, etc). Listings are only visible to clan members — nothing leaks outside. When a deal is closed, mark it as «Sold» with the button on your listing; the owner/admin can delete any listing.'],
            ['en', 'tutorials.topic.clan_system.bullet.6', '**Each CP stays fully private:** The clan never accesses a party\'s internal loot, CP DKP, adena balance, or settings — all that data is 100% private to each CP. What the clan shares: who attended clan events and with what status (approved/pending/rejected), items voluntarily deposited in the vault, and internal market listings. Every CP remains fully independent within the clan.'],

            // ITALIANO
            ['it', 'tutorials.topic.clan_system.intro', 'Il **Sistema Clan** federa più CP sotto un\'unica organizzazione. Da [/clan](/clan) il leader CP crea il clan o si unisce incollando il codice a 8 caratteri di un altro leader. Tre ruoli: **owner** (il fondatore con controllo totale), **admin** (gestisce eventi, vault e mercato) e **membro** (partecipa ma non amministra).'],
            ['it', 'tutorials.topic.clan_system.bullet.0', '**Creare o unirsi a un clan:** Vai su [/clan](/clan). Se la tua CP non appartiene a nessun clan vedrai due schede — «Crea clan» (scegli un nome univoco; il sistema genera automaticamente il codice invito a 8 caratteri) o «Unisciti» (incolla il codice ricevuto dall\'owner). Una volta dentro, l\'owner può copiare, condividere e rigenerare il codice da [/clan/settings](/clan/settings).'],
            ['it', 'tutorials.topic.clan_system.bullet.1', '**Creare e gestire eventi:** In [/clan/events](/clan/events) premi «Nuovo evento». Scegli tipo (Raid Boss, Epic Raid, Assedio, Call to Arms), nome, DKP da assegnare al termine e data/ora opzionale. Gli eventi futuri appaiono in «Programmati» dove i membri inviano RSVP. Flusso completo: admin apre l\'evento → i membri confermano la presenza → i leader CP con permesso approvano i propri membri → l\'admin finalizza → il DKP viene assegnato automaticamente a tutti i presenti «Approvati». La scheda «CP Impact» mostra il ranking di presenze per CP.'],
            ['it', 'tutorials.topic.clan_system.bullet.2', '**Raid Boss Tracker:** In [/clan/raid-bosses](/clan/raid-bosses) gli admin aggiungono boss (nome, livello, ore di respawn — 4h default). Qualsiasi membro può aggiornare lo stato: «Uccidi» registra il timestamp esatto e calcola la finestra di respawn con countdown in tempo reale; «Vivo» (avvistato ma senza ora di morte); «Sconosciuto» per resettare. I boss epici appaiono come card grandi in alto; i normali in tabella. Il countdown si aggiorna ogni secondo ed è visibile a tutto il clan.'],
            ['it', 'tutorials.topic.clan_system.bullet.3', '**DKP Clan:** Il bilancio di ogni membro appare in [/clan/members](/clan/members) (colonna «DKP Clan»). Calcolato automaticamente: eventi finalizzati con presenza «Approvata» aggiungono il DKP configurato; offerte vinte all\'asta del vault le sottraggono; aggiustamenti manuali owner/admin aggiungono o sottraggono. Clicca l\'icona accanto al bilancio per aprire un modal e aggiungere/rimuovere punti con motivazione scritta obbligatoria. Lo storico e l\'opzione di annullare ogni aggiustamento sono disponibili nel profilo membro.'],
            ['it', 'tutorials.topic.clan_system.bullet.4', '**Vault condiviso:** In [/clan/vault](/clan/vault) gli admin depositano oggetti. Una volta nel vault tre destinazioni: «Assegna» (scegli la CP direttamente), «Sorteggio» (il sistema sceglie una CP casuale tra quelle del clan) o «Asta» (imposta offerta minima in DKP e data di chiusura). La scheda «Aste» elenca le aste attive con countdown; qualsiasi membro può offrire; alla chiusura il DKP del vincitore viene detratto automaticamente.'],
            ['it', 'tutorials.topic.clan_system.bullet.5', '**Mercato interno (WTS/WTB):** Da [/clan/market](/clan/market) qualsiasi membro pubblica un annuncio: tipo (WTS = vendo, WTB = cerco), categoria, nome, quantità, prezzo fisso o «Trattabile», e contatto. Visibile solo ai membri del clan. A trattativa conclusa segna l\'annuncio come «Venduto»; admin e owner possono eliminare qualsiasi listato.'],
            ['it', 'tutorials.topic.clan_system.bullet.6', '**Privacy di ogni CP garantita:** Il clan non accede mai al loot interno, DKP CP, adena o impostazioni di ogni party. Si condivide solo: chi ha partecipato agli eventi clan, oggetti depositati volontariamente nel vault e annunci del mercato. Ogni CP rimane completamente indipendente.'],

            // RUSSIAN
            ['ru', 'tutorials.topic.clan_system.intro', '**Система Кланов** объединяет несколько КП в единую организацию. На [/clan](/clan) лидер КП создаёт клан или вступает, вставив 8-значный код от другого лидера. Три роли: **owner** (основатель с полным контролем), **admin** (управляет событиями, складом и рынком) и **member** (участвует, но не администрирует).'],
            ['ru', 'tutorials.topic.clan_system.bullet.0', '**Создать или вступить в клан:** Перейдите на [/clan](/clan). Если ваша КП не принадлежит клану, вы увидите две вкладки — «Создать клан» (выберите уникальное название; система автоматически генерирует 8-значный код приглашения) или «Вступить» (вставьте код от owner\'а клана). Owner может скопировать, передать и перегенерировать код в любое время на [/clan/settings](/clan/settings).'],
            ['ru', 'tutorials.topic.clan_system.bullet.1', '**Создание событий и управление ими:** На [/clan/events](/clan/events) нажмите «Новое событие». Выберите тип (Рейд-босс, Эпик, Осада, Call to Arms), название, DKP за участие и дату/время (необязательно). Будущие события появляются в «Запланированных», где участники отправляют RSVP. Полный цикл: admin открывает событие → участники подтверждают присутствие → лидеры КП с правом одобрения утверждают своих → admin завершает → DKP автоматически начисляется всем утверждённым. Вкладка «CP Impact» показывает рейтинг посещаемости по КП.'],
            ['ru', 'tutorials.topic.clan_system.bullet.2', '**Трекер Рейд-Боссов:** На [/clan/raid-bosses](/clan/raid-bosses) admin добавляет боссов (имя, уровень, часы появления — 4ч по умолчанию). Любой участник обновляет статус: «Убить» фиксирует точное время и запускает обратный отсчёт окна появления в реальном времени; «Жив» (видели, но время смерти неизвестно); «Неизвестно» для сброса. Эпики — крупные карточки вверху; обычные — таблица. Отсчёт виден всему клану и обновляется каждую секунду.'],
            ['ru', 'tutorials.topic.clan_system.bullet.3', '**DKP Клана — как работает баланс:** Баланс каждого участника отображается на [/clan/members](/clan/members) (столбец «DKP Клана»). Рассчитывается автоматически: завершённые события с «Утверждённым» участием прибавляют DKP события; выигранные аукционы вычитают; ручные корректировки owner/admin прибавляют или вычитают. Нажмите иконку корректировки рядом с балансом, введите сумму и обязательное обоснование. Полная история и отмена каждой корректировки доступны в профиле участника.'],
            ['ru', 'tutorials.topic.clan_system.bullet.4', '**Общий Склад — размещение и распределение предметов:** На [/clan/vault](/clan/vault) admin размещает предметы. Три способа распределения: «Назначить» (выбрать КП напрямую), «Жеребьёвка» (система случайно выбирает одну КП из всех клановых) или «Аукцион» (минимальная ставка в DKP и дата закрытия). Вкладка «Аукционы» показывает активные ставки с обратным отсчётом; любой участник делает ставку доступным DKP; при закрытии DKP победителя автоматически вычитается.'],
            ['ru', 'tutorials.topic.clan_system.bullet.5', '**Внутренний Рынок (WTS/WTB):** На [/clan/market](/clan/market) любой участник публикует объявление: тип (WTS = продаю, WTB = ищу), категорию, название, количество, фиксированную цену или «Договорная», и контактные данные. Видно только членам клана. Закрыв сделку, отметьте «Продано»; owner/admin могут удалить любое объявление.'],
            ['ru', 'tutorials.topic.clan_system.bullet.6', '**Каждая КП остаётся приватной:** Клан никогда не получает доступ к внутреннему луту, DKP КП, адене или настройкам группы — эти данные на 100% приватны. Общее для всего клана: кто участвовал в клановых событиях и с каким статусом, предметы, добровольно размещённые на складе, и объявления рынка. Каждая КП остаётся полностью независимой.'],
        ];

        foreach ($rows as [$lang, $key, $value]) {
            DB::table('translations')->updateOrInsert(
                ['language' => $lang, 'key' => $key],
                ['value' => $value, 'updated_at' => now()]
            );
        }
    }

    public function down(): void
    {
        // Translations are not rolled back to avoid data loss
    }
};
